
DROP TABLE PUNTI ;
DROP TABLE TUBI ;
DROP TABLE POZZI ;
DROP TABLE ERRORI_TUBI ;
DROP TABLE TUBI_REL;
DROP TABLE TLAYERS;
DROP TABLE TFORSEZ ;
DROP TABLE CONDOTTE;
DROP TABLE POZZI_CONDOTTE ;
DROP TABLE MONO ;


