
drop  table punti ;
CREATE TABLE punti (
	OBJECTID VARCHAR(20),
    X DOUBLE(12,4),
    Y DOUBLE(12,4),
    Z DOUBLE(12,4)
);

drop  table pozzi;
CREATE TABLE pozzi (
	OBJECTID VARCHAR(20),
    X DOUBLE(12,4),
    Y DOUBLE(12,4),
    Z DOUBLE(12,4),
	RESPTECNI VARCHAR(255),
	QUOINFPOZ DOUBLE(12,4),
	SPES_SUP INTEGER,
	ISTAT_ID VARCHAR(8),
	QUOPUN NUMERIC(128,0) DEFAULT 0,
	CODE VARCHAR(255),
	FORM_CHIU VARCHAR(4),
	MAT_CHIU VARCHAR(4),
	LARG_CHIU INTEGER,
	LUNG_CHIU INTEGER,
	FORMA_SUP VARCHAR(4),
	MAT_SUP VARCHAR(4),
	LARG_SUP INTEGER,
	LUNG_SUP INTEGER,
	FORMA_INF VARCHAR(4),
	MAT_INF VARCHAR(255),
	LARG_INF INTEGER,
	LUNG_INF INTEGER,
	COLPOZ BOOLEAN DEFAULT false,
	TRAVASO INTEGER,
	COP_CHIU BOOLEAN DEFAULT false,
	APP_CHIU BOOLEAN DEFAULT false,
	MAT_COLPOZ VARCHAR(2),
	SUPPOSA VARCHAR(4),
	POS_NODO VARCHAR(255),
	POS_SUP VARCHAR(255),
	QUOTERR DOUBLE(12,4), DEFAULT 0,
	QUOTRAVASO DOUBLE(12,4), DEFAULT 0,
	IMAGE VARCHAR(255),
	DISEGNI VARCHAR(255),
	DATA TIMESTAMP,
	NOTE VARCHAR(2),
	DEN_PUN VARCHAR(2),
	FOTOPOZEST VARCHAR(255),
	FOTOPOZINT VARCHAR(255)
);


drop  table tubi ;
CREATE table tubi (
	OBJECTID VARCHAR(20),
    SEQ INTEGER,
    X DOUBLE(12,4),
    Y DOUBLE(12,4), 
    X1 DOUBLE(12,4),
    Y1 DOUBLE(12,4),
	CODE VARCHAR(255),
	IDPUNTINI INTEGER DEFAULT 0,
	IDPUNTFIN INTEGER DEFAULT 0,
	MATLIN VARCHAR(255),
	FORMSEZ VARCHAR(255),
	ALT_LIN INTEGER DEFAULT 0,
	LARGH_LIN INTEGER DEFAULT 0,
	QUOINI DOUBLE(12,4), DEFAULT 0,
	QUOFIN DOUBLE(12,4), DEFAULT 0,
	DISLINI INTEGER DEFAULT 0,
	DISFIN INTEGER DEFAULT 0,
	TIPFOG VARCHAR(255),
	TIPLINIDR VARCHAR(255),
	POS_TRATTA VARCHAR(255),
	POS_SUP VARCHAR(255),
	NOTE VARCHAR(255),
	LUNG INTEGER DEFAULT 0,
	PENDENZA INTEGER DEFAULT 0,
	DEN_TRONCO VARCHAR(255),
	ENTRA BOOLEAN DEFAULT 0,
	ESCE BOOLEAN DEFAULT 0,
	DAPOZZO VARCHAR(255),
	VERSOPOZZO VARCHAR(255),
	FOTOINT VARCHAR(255),
	FOTOINT VARCHAR(255),
	FONTUBO DOUBLE(12,4)
) ;


insert into pozzi
    (RESPTECNI, OBJECTID, QUOINFPOZ, SPES_SUP, ISTAT_ID, QUOPUN, CODE, FORM_CHIU, MAT_CHIU, LARG_CHIU, 
    LUNG_CHIU, FORMA_SUP, MAT_SUP, LARG_SUP, LUNG_SUP, FORMA_INF, MAT_INF, LARG_INF, LUNG_INF, COLPOZ, 
    TRAVASO, COP_CHIU, APP_CHIU, MAT_COLPOZ, SUPPOSA, POS_NODO, POS_SUP, QUOTERR, QUOTRAVASO, IMAGE, 
    DISEGNI, DATA, NOTE, DEN_PUN, FOTOPOZEST, FOTOPOZINT )
SELECT 
    RESPTECNI, OBJECTID, QUOINFPOZ, SPES_SUP, ISTAT_ID, QUOPUN, CODE, FORM_CHIU, MAT_CHIU, LARG_CHIU, 
    LUNG_CHIU, FORMA_SUP, MAT_SUP, LARG_SUP, LUNG_SUP, FORMA_INF, MAT_INF, LARG_INF, LUNG_INF, COLPOZ, 
    TRAVASO, COP_CHIU, APP_CHIU, MAT_COLPOZ, SUPPOSA, POS_NODO, POS_SUP, QUOTERR, QUOTRAVASO, IMAGE, 
    DISEGNI, DATA, NOTE, DEN_PUN, FOTOPOZEST, FOTOPOZINT 
FROM unionepazzitubislim1;

insert into tubi 
    (OBJECTID , SEQ ,
  CODE, IDPUNTINI, IDPUNTFIN, MATLIN, FORMSEZ, ALT_LIN, LARGH_LIN, QUOINI, QUOFIN, DISLINI, DISFIN, 
    TIPFOG, TIPLINIDR, POS_TRATTA, POS_SUP, NOTE, LUNG, PENDENZA, DEN_TRONCO, ENTRA, ESCE, DAPOZZO, 
    VERSOPOZZO, FOTOINT, FONTUBO)
SELECT    
    OBJECTID , 1,1CODE, 1IDPUNTINI, 1IDPUNTFIN, 1MATLIN, 1FORMSEZ, 1ALT_LIN, 1LARGH_LIN, 1QUOINI, 1QUOFIN, 1DISLINI, 
    1DISFIN, 1TIPFOG, 1TIPLINIDR, 1POS_TRATTA, 1POS_SUP, 1NOTE, 1LUNG, 1PENDENZA, 1DEN_TRONCO, 1ENTRA, 
    1ESCE, 1DAPOZZO, 1VERSOPOZZO, 1FOTOINT, 1FONTUBO
FROM unionepazzitubislim1;

insert into tubi 
    (OBJECTID , SEQ ,CODE, IDPUNTINI, IDPUNTFIN, MATLIN, FORMSEZ, ALT_LIN, LARGH_LIN, QUOINI, QUOFIN, DISLINI, DISFIN, 
    TIPFOG, TIPLINIDR, POS_TRATTA, POS_SUP, NOTE, LUNG, PENDENZA, DEN_TRONCO, ENTRA, ESCE, DAPOZZO, 
    VERSOPOZZO, FOTOINT, FONTUBO)
SELECT    
    OBJECTID , 2,2CODE, 2IDPUNTINI, 2IDPUNTFIN, 2MATLIN, 2FORMSEZ, 2ALT_LIN, 2LARGH_LIN, 2QUOINI, 2QUOFIN, 2DISLINI, 
    2DISFIN, 2TIPFOG, 2TIPLINIDR, 2POS_TRATTA, 2POS_SUP, 2NOTE, 2LUNG, 2PENDENZA, 2DEN_TRONCO, 2ENTRA, 
    2ESCE, 2DAPOZZO, 2VERSOPOZZO, 2FOTOINT, 2FONTUBO
FROM unionepazzitubislim1;

insert into tubi 
    (OBJECTID , SEQ ,CODE, IDPUNTINI, IDPUNTFIN, MATLIN, FORMSEZ, ALT_LIN, LARGH_LIN, QUOINI, QUOFIN, DISLINI, DISFIN, 
    TIPFOG, TIPLINIDR, POS_TRATTA, POS_SUP, NOTE, LUNG, PENDENZA, DEN_TRONCO, ENTRA, ESCE, DAPOZZO, 
    VERSOPOZZO, FOTOINT, FONTUBO)
SELECT
    OBJECTID , 3,3CODE, 3IDPUNTINI, 3IDPUNTFIN, 3MATLIN, 3FORMSEZ, 3ALT_LIN, 3LARGH_LIN, 3QUOINI, 3QUOFIN, 3DISLINI, 
    3DISFIN, 3TIPFOG, 3TIPLINIDR, 3POS_TRATTA, 3POS_SUP, 3NOTE, 3LUNG, 3PENDENZA, 3DEN_TRONCO, 3ENTRA, 
    3ESCE, 3DAPOZZO, 3VERSOPOZZO, 3FOTOINT, 3FONTUBO
FROM unionepazzitubislim1;

insert into tubi 
    (OBJECTID , SEQ ,CODE, IDPUNTINI, IDPUNTFIN, MATLIN, FORMSEZ, ALT_LIN, LARGH_LIN, QUOINI, QUOFIN, DISLINI, DISFIN, 
    TIPFOG, TIPLINIDR, POS_TRATTA, POS_SUP, NOTE, LUNG, PENDENZA, DEN_TRONCO, ENTRA, ESCE, DAPOZZO, 
    VERSOPOZZO, FOTOINT, FONTUBO)
SELECT    
    OBJECTID , 4,4CODE, 4IDPUNTINI, 4IDPUNTFIN, 4MATLIN, 4FORMSEZ, 4ALT_LIN, 4LARGH_LIN, 4QUOINI, 4QUOFIN, 4DISLINI, 
    4DISFIN, 4TIPFOG, 4TIPLINIDR, 4POS_TRATTA, 4POS_SUP, 4NOTE, 4LUNG, 4PENDENZA, 4DEN_TRONCO, 4ENTRA, 
    4ESCE, 4DAPOZZO, 4VERSOPOZZO, 4FOTOINT, 4FONTUBO
FROM unionepazzitubislim1;

insert into tubi 
    (OBJECTID , SEQ ,CODE, IDPUNTINI, IDPUNTFIN, MATLIN, FORMSEZ, ALT_LIN, LARGH_LIN, QUOINI, QUOFIN, DISLINI, DISFIN, 
    TIPFOG, TIPLINIDR, POS_TRATTA, POS_SUP, NOTE, LUNG, PENDENZA, DEN_TRONCO, ENTRA, ESCE, DAPOZZO, 
    VERSOPOZZO, FOTOINT, FONTUBO)
SELECT    
    OBJECTID , 5,5CODE, 5IDPUNTINI, 5IDPUNTFIN, 5MATLIN, 5FORMSEZ, 5ALT_LIN, 5LARGH_LIN, 5QUOINI, 5QUOFIN, 5DISLINI, 
    5DISFIN, 5TIPFOG, 5TIPLINIDR, 5POS_TRATTA, 5POS_SUP, 5NOTE, 5LUNG, 5PENDENZA, 5DEN_TRONCO, 5ENTRA, 
    5ESCE, 5DAPOZZO, 5VERSOPOZZO, 5FOTOINT, 5FONTUBO
FROM unionepazzitubislim1;

insert into tubi 
    (OBJECTID , SEQ ,CODE, IDPUNTINI, IDPUNTFIN, MATLIN, FORMSEZ, ALT_LIN, LARGH_LIN, QUOINI, QUOFIN, DISLINI, DISFIN, 
    TIPFOG, TIPLINIDR, POS_TRATTA, POS_SUP, NOTE, LUNG, PENDENZA, DEN_TRONCO, ENTRA, ESCE, DAPOZZO, 
    VERSOPOZZO, FOTOINT, FONTUBO)
SELECT    
    OBJECTID , 6,6CODE, 6IDPUNTINI, 6IDPUNTFIN, 6MATLIN, 6FORMSEZ, 6ALT_LIN, 6LARGH_LIN, 6QUOINI, 6QUOFIN, 6DISLINI, 
    6DISFIN, 6TIPFOG, 6TIPLINIDR, 6POS_TRATTA, 6POS_SUP, 6NOTE, 6LUNG, 6PENDENZA, 6DEN_TRONCO, 6ENTRA, 
    6ESCE, 6DAPOZZO, 6VERSOPOZZO, 6FOTOINT, 6FONTUBO
FROM unionepazzitubislim1;
