INSERT INTO POZZI
    (RESPTECNI, OBJECTID, QUOINFPOZ, SPES_SUP, ISTAT_ID, QUOPUN, CODE, FORM_CHIU, MAT_CHIU, LARG_CHIU, 
    LUNG_CHIU, FORMA_SUP, MAT_SUP, LARG_SUP, LUNG_SUP, FORMA_INF, MAT_INF, LARG_INF, LUNG_INF, COLPOZ, 
    TRAVASO, COP_CHIU, APP_CHIU, MAT_COLPOZ, SUPPOSA, POS_NODO, POS_SUP, QUOTERR, QUOTRAVASO, TIMAGE, 
    DISEGNI, DATA, TNOTE, DEN_PUN, FOTOPOZEST, FOTOPOZINT, BLOCCO, LAYER )
SELECT 
    RESPTECNI, OBJECTID, QUOINFPOZ, SPES_SUP, ISTAT_ID, QUOPUN, CODE, FORM_CHIU, MAT_CHIU, LARG_CHIU, 
    LUNG_CHIU, FORMA_SUP, MAT_SUP, LARG_SUP, LUNG_SUP, FORMA_INF, MAT_INF, LARG_INF, LUNG_INF, COLPOZ, 
    TRAVASO, COP_CHIU, APP_CHIU, MAT_COLPOZ, SUPPOSA, POS_NODO, POS_SUP, QUOTERR, QUOTRAVASO, `IMAGE`, 
    DISEGNI, DATA, `NOTE`, DEN_PUN, FOTOPOZEST, FOTOPOZINT, 'PF', '20_F-POZZETTI-VARI' 
FROM UNIONEPAZZITUBISLIM1;

INSERT INTO TUBI 
    (OBJECTID , SEQ, ISTAT_ID, DATA,
    CODE, IDPUNTINI, 
    IDPUNTFIN, MATLIN, 
    FORMSEZ, ALT_LIN, 
    LARGH_LIN, QUOINI, 
    QUOFIN, DISLINI, 
    DISFIN, TIPFOG, 
    TIPLINIDR, POS_TRATTA, 	
    POS_SUP, TNOTE, 
    TLUNG, PENDENZA, 
    DEN_TRONCO, ENTRA, 
    ESCE, DAPOZZO, 
    VERSOPOZZO, FOTOINT, FONTUBO)
SELECT    
    OBJECTID , 1, ISTAT_ID, DATA,
    `1CODE`, `1IDPUNTINI`, 
    `1IDPUNTFIN`, `1MATLIN`, 
    `1FORMSEZ`, `1ALT_LIN`, 
    `1LARGH_LIN`, `1QUOINI`, 
    `1QUOFIN`, `1DISLINI`, 
    `1DISFIN`, `1TIPFOG`, 
    `1TIPLINIDR`, `1POS_TRATTA`, 
    `1POS_SUP`, `1NOTE`, 
    `1LUNG`, `1PENDENZA`, 
    `1DEN_TRONCO`, `1ENTRA`, 
    `1ESCE`, `1DAPOZZO`, 
    `1VERSOPOZZO`, `1FOTOINT`, `1FONTUBO`
FROM UNIONEPAZZITUBISLIM1;

INSERT INTO TUBI 
    (OBJECTID , SEQ, ISTAT_ID, DATA,
	CODE, IDPUNTINI, 
	IDPUNTFIN, MATLIN, 
	FORMSEZ, ALT_LIN, 
	LARGH_LIN, QUOINI, 
	QUOFIN, DISLINI, 
	DISFIN, TIPFOG, 
	TIPLINIDR, POS_TRATTA, 
	POS_SUP, TNOTE, 
	TLUNG, PENDENZA, 
	DEN_TRONCO, ENTRA, 
	ESCE, DAPOZZO, 
	VERSOPOZZO, FOTOINT, FONTUBO)
SELECT    
	OBJECTID , 2, ISTAT_ID, DATA,
	`2CODE`, `2IDPUNTINI`, 
	`2IDPUNTFIN`, `2MATLIN`, 
	`2FORMSEZ`, `2ALT_LIN`, 
	`2LARGH_LIN`, `2QUOINI`, 
	`2QUOFIN`, `2DISLINI`, 
	`2DISFIN`, `2TIPFOG`, 
	`2TIPLINIDR`, `2POS_TRATTA`, 
	`2POS_SUP`, `2NOTE`, 
	`2LUNG`, `2PENDENZA`, 
	`2DEN_TRONCO`, `2ENTRA`, 
	`2ESCE`, `2DAPOZZO`, 
	`2VERSOPOZZO`, `2FOTOINT`, `2FONTUBO`
FROM UNIONEPAZZITUBISLIM1;


INSERT INTO TUBI 
    (OBJECTID , SEQ, ISTAT_ID, DATA,
	CODE, IDPUNTINI, 
	IDPUNTFIN, MATLIN, 
	FORMSEZ, ALT_LIN, 
	LARGH_LIN, QUOINI, 
	QUOFIN, DISLINI, 
	DISFIN, TIPFOG, 
	TIPLINIDR, POS_TRATTA, 
	POS_SUP, TNOTE, 
	TLUNG, PENDENZA, 
	DEN_TRONCO, ENTRA, 
	ESCE, DAPOZZO, 
	VERSOPOZZO, FOTOINT, FONTUBO)
SELECT    
	OBJECTID , 3, ISTAT_ID, DATA,
	`3CODE`, `3IDPUNTINI`, 
	`3IDPUNTFIN`, `3MATLIN`, 
	`3FORMSEZ`, `3ALT_LIN`, 
	`3LARGH_LIN`, `3QUOINI`, 
	`3QUOFIN`, `3DISLINI`, 
	`3DISFIN`, `3TIPFOG`, 
	`3TIPLINIDR`, `3POS_TRATTA`, 
	`3POS_SUP`, `3NOTE`, 
	`3LUNG`, `3PENDENZA`, 
	`3DEN_TRONCO`, `3ENTRA`, 
	`3ESCE`, `3DAPOZZO`, 
	`3VERSOPOZZO`, `3FOTOINT`, `3FONTUBO`
FROM UNIONEPAZZITUBISLIM1;


INSERT INTO TUBI 
    (OBJECTID , SEQ, ISTAT_ID, DATA,
	CODE, IDPUNTINI, 
	IDPUNTFIN, MATLIN, 
	FORMSEZ, ALT_LIN, 
	LARGH_LIN, QUOINI, 
	QUOFIN, DISLINI, 
	DISFIN, TIPFOG, 
	TIPLINIDR, POS_TRATTA, 
	POS_SUP, TNOTE, 
	TLUNG, PENDENZA, 
	DEN_TRONCO, ENTRA, 
	ESCE, DAPOZZO, 
	VERSOPOZZO, FOTOINT, FONTUBO)
SELECT    
	OBJECTID , 4, ISTAT_ID, DATA,
	`4CODE`, `4IDPUNTINI`, 
	`4IDPUNTFIN`, `4MATLIN`, 
	`4FORMSEZ`, `4ALT_LIN`, 
	`4LARGH_LIN`, `4QUOINI`, 
	`4QUOFIN`, `4DISLINI`, 
	`4DISFIN`, `4TIPFOG`, 
	`4TIPLINIDR`, `4POS_TRATTA`, 
	`4POS_SUP`, `4NOTE`, 
	`4LUNG`, `4PENDENZA`, 
	`4DEN_TRONCO`, `4ENTRA`, 
	`4ESCE`, `4DAPOZZO`, 
	`4VERSOPOZZO`, `4FOTOINT`, `4FONTUBO`
FROM UNIONEPAZZITUBISLIM1;

INSERT INTO TUBI 
    (OBJECTID , SEQ, ISTAT_ID, DATA,
	CODE, IDPUNTINI, 
	IDPUNTFIN, MATLIN, 
	FORMSEZ, ALT_LIN, 
	LARGH_LIN, QUOINI, 
	QUOFIN, DISLINI, 
	DISFIN, TIPFOG, 
	TIPLINIDR, POS_TRATTA, 
	POS_SUP, TNOTE, 
	TLUNG, PENDENZA, 
	DEN_TRONCO, ENTRA, 
	ESCE, DAPOZZO, 
	VERSOPOZZO, FOTOINT, FONTUBO)
SELECT    
	OBJECTID , 5, ISTAT_ID, DATA,
	`5CODE`, `5IDPUNTINI`, 
	`5IDPUNTFIN`, `5MATLIN`, 
	`5FORMSEZ`, `5ALT_LIN`, 
	`5LARGH_LIN`, `5QUOINI`, 
	`5QUOFIN`, `5DISLINI`, 
	`5DISFIN`, `5TIPFOG`, 
	`5TIPLINIDR`, `5POS_TRATTA`, 
	`5POS_SUP`, `5NOTE`, 
	`5LUNG`, `5PENDENZA`, 
	`5DEN_TRONCO`, `5ENTRA`, 
	`5ESCE`, `5DAPOZZO`, 
	`5VERSOPOZZO`, `5FOTOINT`, `5FONTUBO`
FROM UNIONEPAZZITUBISLIM1;

INSERT INTO TUBI 
    (OBJECTID , SEQ, ISTAT_ID, DATA,
	CODE, IDPUNTINI, 
	IDPUNTFIN, MATLIN, 
	FORMSEZ, ALT_LIN, 
	LARGH_LIN, QUOINI, 
	QUOFIN, DISLINI, 
	DISFIN, TIPFOG, 
	TIPLINIDR, POS_TRATTA, 
	POS_SUP, TNOTE, 
	TLUNG, PENDENZA, 
	DEN_TRONCO, ENTRA, 
	ESCE, DAPOZZO, 
	VERSOPOZZO, FOTOINT, FONTUBO)
SELECT    
	OBJECTID , 6, ISTAT_ID, DATA,
	`6CODE`, `6IDPUNTINI`, 
	`6IDPUNTFIN`, `6MATLIN`, 
	`6FORMSEZ`, `6ALT_LIN`, 
	`6LARGH_LIN`, `6QUOINI`, 
	`6QUOFIN`, `6DISLINI`, 
	`6DISFIN`, `6TIPFOG`, 
	`6TIPLINIDR`, `6POS_TRATTA`, 
	`6POS_SUP`, `6NOTE`, 
	`6LUNG`, `6PENDENZA`, 
	`6DEN_TRONCO`, `6ENTRA`, 
	`6ESCE`, `6DAPOZZO`, 
	`6VERSOPOZZO`, `6FOTOINT`, `6FONTUBO`
FROM UNIONEPAZZITUBISLIM1;


UPDATE POZZI  SET x = 0.0 , y = 0.0 , z = 0.0 where x is null;
UPDATE TUBI  SET x = 0.0 , y = 0.0 where x is null;

UPDATE POZZI INNER JOIN PUNTI ON PUNTI.OBJECTID = POZZI.OBJECTID  
SET 
	POZZI.X = PUNTI.X ,
	POZZI.Y = PUNTI.Y ,
	POZZI.Z =  PUNTI.Z 
WHERE POZZI.X = 0 ;

UPDATE POZZI INNER JOIN TUBI ON TUBI.OBJECTID = POZZI.OBJECTID  
SET 
	POZZI.BLOCCO = 'PFB' 
WHERE TUBI.TIPFOG = '02' and (TUBI.ENTRA OR TUBI.ESCE) ;

UPDATE POZZI  SET x = 5 * ID , y = 5 * ID , z = 0.0 where x = 0.0;

UPDATE POZZI  SET QUOPUN = Z where ID > -1000;
UPDATE POZZI  SET QUOINFPOZ = (Z - (QUOINFPOZ/100)) where ID > -1000;
UPDATE POZZI  SET QUOTRAVASO = (Z - (TRAVASO/100))  where ID > -1000;
UPDATE POZZI  SET QUOTERR = Z   where ID > -1000;
 

UPDATE TUBI INNER JOIN POZZI ON POZZI.OBJECTID = TUBI.OBJECTID  
SET 	
	TUBI.X = POZZI.X ,
	TUBI.Y = POZZI.Y ,
	TUBI.Z = POZZI.Z
WHERE TUBI.X = 0 ;

UPDATE TUBI zi SET 
x1 = x + (5 * cos(0) ),
y1 = y + (5 * sin(0) )
WHERE SEQ = 1 ;

UPDATE TUBI zi SET 
x1 = x + (5 * cos(3.14159265359/8) ),
y1 = y + (5 * sin(3.14159265359/8) )
WHERE SEQ = 2 ;

UPDATE TUBI zi SET 
x1 = x + (5 * cos(3.14159265359/6) ),
y1 = y + (5 * sin(3.14159265359/6) )
WHERE SEQ = 3 ;

UPDATE TUBI zi SET 
x1 = x + (5 * cos(3.14159265359/4) ),
y1 = y + (5 * sin(3.14159265359/4) )
WHERE SEQ = 4 ;

UPDATE TUBI zi SET 
x1 = x + (5 * cos(3.14159265359/3) ),
y1 = y + (5 * sin(3.14159265359/3) )
WHERE SEQ = 5 ;

UPDATE TUBI zi SET 
x1 = x + (5 * cos(3.14159265359/2) ),
y1 = y + (5 * sin(3.14159265359/2) )
WHERE SEQ = 6 ;

UPDATE TUBI SET DAPOZZO = OBJECTID WHERE ESCE = -1 AND DAPOZZO IS NULL;
UPDATE TUBI SET VERSOPOZZO = OBJECTID WHERE ENTRA = -1 AND VERSOPOZZO IS NULL;

DELETE FROM TUBI WHERE ENTRA = 0 AND  ESCE = 0 ;

INSERT INTO TUBI_REL (INI, FIN)
 SELECT 
 	INI.ID AS INI ,FIN.ID AS FIN
 FROM 
 	TUBI INI 
 	INNER JOIN  TUBI FIN ON  INI.VERSOPOZZO = FIN.OBJECTID AND FIN.DAPOZZO=INI.OBJECTID
 WHERE INI.ESCE;
 
 
INSERT INTO ERRORI_TUBI (ERRORE)
 SELECT 
   INI.OBJECTID & '-' & INI.SEQ & ' MANCA CORRISPONDENTE TUBO IN POZZO ' & INI.VERSOPOZZO AS ERRORE
 FROM 
 	TUBI INI 
 	LEFT OUTER JOIN  TUBI FIN ON  INI.VERSOPOZZO = FIN.OBJECTID AND FIN.DAPOZZO=INI.OBJECTID
 WHERE INI.VERSOPOZZO IS NOT NULL AND FIN.ID IS NULL;
 
 
 INSERT INTO ERRORI_TUBI (ERRORE)
 SELECT 
 	INI.OBJECTID & '-' & INI.SEQ & ' MANCA CORRISPONDENTE TUBO IN POZZO ' & INI.DAPOZZO AS ERRORE
 FROM 
 	TUBI INI 
 	LEFT OUTER JOIN  TUBI FIN ON  INI.DAPOZZO = FIN.OBJECTID AND FIN.VERSOPOZZO = INI.OBJECTID
 WHERE INI.DAPOZZO IS NOT NULL AND FIN.ID IS NULL;
 
INSERT INTO ERRORI_TUBI (ERRORE)
 SELECT 
 	INI.OBJECTID & '-' & INI.SEQ & '<>' & FIN.OBJECTID & '-' & FIN.SEQ & ' DIFERISOCONO PER TIPO' AS ERRORE
 FROM 
 	(((TUBI AS INI) 
 	INNER JOIN TUBI_REL AS SE ON SE.`INI` = INI.`ID`)
 	INNER JOIN  TUBI AS FIN ON  SE.`FIN` = FIN.`ID` )
 WHERE INI.CODE <> FIN.CODE ;
 
 
INSERT INTO ERRORI_TUBI (ERRORE)
 SELECT 
 	INI.OBJECTID & '-' & INI.SEQ & '<>' & FIN.OBJECTID & '-' & FIN.SEQ &  ' DIFERISOCONO PER MATERIALE' AS ERRORE
 FROM 
 	(((TUBI AS INI) 
 	INNER JOIN TUBI_REL AS SE ON SE.`INI` = INI.`ID`)
 	INNER JOIN  TUBI AS FIN ON  SE.`FIN` = FIN.`ID` )
 WHERE INI.MATLIN <> FIN.MATLIN ;
 
INSERT INTO ERRORI_TUBI (ERRORE)
 SELECT 
 	INI.OBJECTID & '-' & INI.SEQ & '<>' & FIN.OBJECTID & '-' & FIN.SEQ &  ' DIFERISOCONO PER FORMA' AS ERRORE
 FROM 
 	(((TUBI AS INI) 
 	INNER JOIN TUBI_REL AS SE ON SE.`INI` = INI.`ID`)
 	INNER JOIN  TUBI AS FIN ON  SE.`FIN` = FIN.`ID` )
 WHERE INI.FORMSEZ <> FIN.FORMSEZ;
 
INSERT INTO ERRORI_TUBI (ERRORE)
 SELECT 
 	INI.OBJECTID & '-' & INI.SEQ & '<>' & FIN.OBJECTID & '-' & FIN.SEQ &  ' DIFERISOCONO PER FORMA' AS ERRORE
 FROM 
 	(((TUBI AS INI) 
 	INNER JOIN TUBI_REL AS SE ON SE.`INI` = INI.`ID`)
 	INNER JOIN  TUBI AS FIN ON  SE.`FIN` = FIN.`ID` )
 WHERE INI.LARGH_LIN <> FIN.LARGH_LIN;

INSERT INTO CONDOTTE ( X, Y, X1, Y1, DH, 
    INI_ID, FIN_ID, OBJ_ID, ISTAT_ID, CODE, IDPUNINI, IDPUNFIN, 
    IDLININI, MATLIN, FORMSEZ, ALT_LIN, LARGH_LIN, QUOINI, QUOFIN, 
    DISLINI, DISLFIN, TIPFOG, TIPLINIDR, POS_TRATTA, POS_SUP, 
    FOTOINT, [DATA], TNOTE, TLUNG, PENDENZA, DEN_TRONCO, 
    LAYER, SECONDARY, MATERIALE, FORMA) 
SELECT 
 INI.X AS "X",
 INI.Y AS "Y",
 FIN.X AS "X1",
 FIN.Y AS "Y1",
 ((INI.Z - (INI.FONTUBO / 100)) - (FIN.Z - (FIN.FONTUBO / 100))) as "DH",
 INI.OBJECTID AS "INI_ID",
 FIN.OBJECTID AS "FIN_ID",
 INI.OBJECTID & '-' & FIN.OBJECTID AS "OBJ_ID",
 INI.ISTAT_ID as "ISTAT_ID",
 INI.CODE as "CODE",
 INI.OBJECTID  as "IDPUNINI",
 FIN.OBJECTID as "IDPUNFIN",
 '' as "IDLININI",
 INI.MATLIN as "MATLIN",
 INI.FORMSEZ as "FORSEZ",
 INI.ALT_LIN  as "ALT_LIN",
 INI.LARGH_LIN as "LARG_LIN",
 (INI.Z - (INI.FONTUBO / 100)) as "QUOINI",
 (FIN.Z - (FIN.FONTUBO / 100)) as "QUOFIN",
 INI.FONTUBO as "DISLINI",
 FIN.FONTUBO as "DISLFIN",
 INI.TIPFOG as "TIPFOG",
 INI.TIPLINIDR as "TIPLINIDR",
 INI.POS_TRATTA as "POS_TRATTA",
 INI.POS_SUP as "POS_SUP",
 INI.FOTOINT as "IMAGE",
 INI.[DATA] as "DATA",
 INI.TNOTE as "NOTE",
 INI.TLUNG as "LUNG",
 INI.PENDENZA as "PENDENZA",
 INI.DEN_TRONCO as "DEN_TRONC",
 TL.[VAL] as "LAYER",
 M.MAT & ' ' & FS.[VAL] & INI.ALT_LIN & 'x' & INI.LARGH_LIN as "SECONDARY",
 MAT.DESCRIZIONE as MATERIALE,
 FO.FORSEZ as FORMAbd
FROM 
((((((((TUBI AS INI ) 
	INNER JOIN L_MAT 	AS M	ON (INI.`MATLIN` = M.`ID`) )
	INNER JOIN TLAYERS 	AS TL	ON (INI.`TIPFOG` = TL.`COD`) )
	INNER JOIN TFORSEZ 	AS FS	ON (INI.`FORMSEZ` = FS.`COD`) )
	INNER JOIN TUBI_REL	AS SE	ON (SE.`INI` = INI.`ID`) )
	INNER JOIN TUBI 	AS FIN	ON (SE.`FIN` = FIN.`ID`) )
	INNER JOIN MAT2  MAT on (INI.MATLIN = MAT.ID))
	INNER JOIN FORSEZ FO on (INI.FORMSEZ = FO.ID))
WHERE INI.FORMSEZ <> '02'; 

INSERT INTO CONDOTTE ( X, Y, X1, Y1, DH, 
    INI_ID, FIN_ID, OBJ_ID, ISTAT_ID, CODE, IDPUNINI, IDPUNFIN, 
    IDLININI, MATLIN, FORMSEZ, ALT_LIN, LARGH_LIN, QUOINI, QUOFIN, 
    DISLINI, DISLFIN, TIPFOG, TIPLINIDR, POS_TRATTA, POS_SUP, 
    FOTOINT, [DATA], TNOTE, TLUNG, PENDENZA, DEN_TRONCO, 
    LAYER, SECONDARY, MATERIALE, FORMA) 
SELECT 
 INI.X AS "X",
 INI.Y AS "Y",
 FIN.X AS "X1",
 FIN.Y AS "Y1",
 ((INI.Z - (INI.FONTUBO / 100)) - (FIN.Z - (FIN.FONTUBO / 100))) as "DH",
 INI.OBJECTID AS "INI_ID",
 FIN.OBJECTID AS "FIN_ID",
 INI.OBJECTID & '-' & FIN.OBJECTID AS "OBJ_ID",
 INI.ISTAT_ID as "ISTAT_ID",
 INI.CODE as "CODE",
 INI.OBJECTID  as "IDPUNINI",
 FIN.OBJECTID as "IDPUNFIN",
 '' as "IDLININI",
 INI.MATLIN as "MATLIN",
 INI.FORMSEZ as "FORSEZ",
 INI.ALT_LIN  as "ALT_LIN",
 INI.LARGH_LIN as "LARG_LIN",
 (INI.Z - (INI.FONTUBO / 100)) as "QUOINI",
 (FIN.Z - (FIN.FONTUBO / 100)) as "QUOFIN",
 INI.FONTUBO as "DISLINI",
 FIN.FONTUBO as "DISLFIN",
 INI.TIPFOG as "TIPFOG",
 INI.TIPLINIDR as "TIPLINIDR",
 INI.POS_TRATTA as "POS_TRATTA",
 INI.POS_SUP as "POS_SUP",
 INI.FOTOINT as "IMAGE",
 INI.[DATA] as "DATA",
 INI.TNOTE as "NOTE",
 INI.TLUNG as "LUNG",
 INI.PENDENZA as "PENDENZA",
 INI.DEN_TRONCO as "DEN_TRONC",
 TL.[VAL] as "LAYER",
 M.MAT & ' ' & FS.[VAL] & INI.ALT_LIN  as "SECONDARY",
 MAT.DESCRIZIONE as MATERIALE,
 FO.FORSEZ as FORMA
FROM 
((((((((TUBI AS INI ) 
	INNER JOIN L_MAT 	AS M	ON (INI.`MATLIN` = M.`ID`) )
	INNER JOIN TLAYERS 	AS TL	ON (INI.`TIPFOG` = TL.`COD`) )
	INNER JOIN TFORSEZ 	AS FS	ON (INI.`FORMSEZ` = FS.`COD`) )
	INNER JOIN TUBI_REL	AS SE	ON (SE.`INI` = INI.`ID`) )
	INNER JOIN TUBI 	AS FIN	ON (SE.`FIN` = FIN.`ID`) )
	INNER JOIN MAT2  MAT on (INI.MATLIN = MAT.ID))
	INNER JOIN FORSEZ FO on (INI.FORMSEZ = FO.ID))
WHERE INI.FORMSEZ = '02'; 


INSERT into  POZZI_CONDOTTE (ID_CONDOTTA, ID_POZZO) SELECT ID_KEY, IDPUNINI from CONDOTTE; 
INSERT into  POZZI_CONDOTTE (ID_CONDOTTA, ID_POZZO) SELECT ID_KEY, IDPUNFIN from CONDOTTE;