SELECT 
 INI.X AS "X",
 INI.Y AS "Y",
 FIN.X AS "X1",
 FIN.Y AS "Y1",
 ((INI.Z - (INI.FONTUBO / 100)) - (FIN.Z - (FIN.FONTUBO / 100))) as "DH",
 INI.OBJECTID & '-' & FIN.OBJECTID AS "OBJ_ID",
 INI.ISTAT_ID as "ISTAT_ID",
 INI.CODE as "CODE",
 INI.OBJECTID  as "IDPUNINI",
 FIN.OBJECTID as "IDPUNFIN",
 '' as "IDLININI",
 INI.MATLIN as "MATLIN",
 INI.FORMSEZ as "FORSEZ",
 INI.ALT_LIN  as "ALT_LIN",
 INI.LARGH_LIN as "LARG_LIN",
 (INI.Z - (INI.FONTUBO / 100)) as "QUOINI",
 (FIN.Z - (FIN.FONTUBO / 100)) as "QUOFIN",
 INI.FONTUBO as "DISLINI",
 FIN.FONTUBO as "DISLFIN",
 INI.TIPFOG as "TIPFOG",
 INI.TIPLINIDR as "TIPLINIDR",
 INI.POS_TRATTA as "POS_TRATTA",
 INI.POS_SUP as "POS_SUP",
 INI.FOTOINT as "IMAGE",
 INI.[DATA] as "DATA",
 INI.TNOTE as "NOTE",
 INI.TLUNG as "LUNG",
 INI.PENDENZA as "PENDENZA",
 INI.DEN_TRONCO as "DEN_TRONC",
 TL.[VAL] as "LAYER",
 M.MAT & ' ' & FS.[VAL] & INI.ALT_LIN & 'x' & INI.LARGH_LIN as "SECONDARY" 
FROM 
((((((TUBI AS INI ) 
	INNER JOIN L_MAT 	AS M	ON (INI.`MATLIN` = M.`ID`) )
	INNER JOIN TLAYERS 	AS TL	ON (INI.`TIPFOG` = TL.`COD`) )
	INNER JOIN TFORSEZ 	AS FS	ON (INI.`FORMSEZ` = FS.`COD`) )
	INNER JOIN TUBI_REL	AS SE	ON (SE.`INI` = INI.`ID`) )
	INNER JOIN TUBI 	AS FIN	ON (SE.`FIN` = FIN.`ID`) )
WHERE INI.FORMSEZ <> '02'; 

SELECT 
 INI.X AS "X",
 INI.Y AS "Y",
 FIN.X AS "X1",
 FIN.Y AS "Y1",
 ((INI.Z - (INI.FONTUBO / 100)) - (FIN.Z - (FIN.FONTUBO / 100))) as "DH",
 INI.OBJECTID & '-' & FIN.OBJECTID AS "OBJ_ID",
 INI.ISTAT_ID as "ISTAT_ID",
 INI.CODE as "CODE",
 INI.OBJECTID  as "IDPUNINI",
 FIN.OBJECTID as "IDPUNFIN",
 '' as "IDLININI",
 INI.MATLIN as "MATLIN",
 INI.FORMSEZ as "FORSEZ",
 INI.ALT_LIN  as "ALT_LIN",
 INI.LARGH_LIN as "LARG_LIN",
 (INI.Z - (INI.FONTUBO / 100)) as "QUOINI",
 (FIN.Z - (FIN.FONTUBO / 100)) as "QUOFIN",
 INI.FONTUBO as "DISLINI",
 FIN.FONTUBO as "DISLFIN",
 INI.TIPFOG as "TIPFOG",
 INI.TIPLINIDR as "TIPLINIDR",
 INI.POS_TRATTA as "POS_TRATTA",
 INI.POS_SUP as "POS_SUP",
 INI.FOTOINT as "IMAGE",
 INI.[DATA] as "DATA",
 INI.TNOTE as "NOTE",
 INI.TLUNG as "LUNG",
 INI.PENDENZA as "PENDENZA",
 INI.DEN_TRONCO as "DEN_TRONC",
 TL.[VAL] as "LAYER",
 M.MAT & ' ' & FS.[VAL] & INI.ALT_LIN  as "SECONDARY" 
FROM 
((((((TUBI AS INI ) 
	INNER JOIN L_MAT 	AS M	ON (INI.`MATLIN` = M.`ID`) )
	INNER JOIN TLAYERS 	AS TL	ON (INI.`TIPFOG` = TL.`COD`) )
	INNER JOIN TFORSEZ 	AS FS	ON (INI.`FORMSEZ` = FS.`COD`) )
	INNER JOIN TUBI_REL	AS SE	ON (SE.`INI` = INI.`ID`) )
	INNER JOIN TUBI 	AS FIN	ON (SE.`FIN` = FIN.`ID`) )
WHERE INI.FORMSEZ = '02'; 

