UPDATE CONDOTTE set PENDENZA = (dh / TLUNG ) *100  where TLUNG <> 0;

INSERT into MONO( P_OBJECTID, P_ISTAT_ID, P_QUOINFPOZ, P_QUOPUN, P_QUOTERR, P_QUOTRAVASO, P_TRAVASO, P_SPES_SUP, P_LARG_CHIU, P_LUNG_CHIU, P_LARG_SUP, P_LUNG_SUP, P_LARG_INF, P_LUNG_INF, P_COP_CHIU, P_APP_CHIU, P_COLPOZ, p_CODE, p_FORMA_SUP, p_FORMA_INF, p_FORM_CHIU, p_MAT_CHIU, p_MAT_SUP, p_MAT_INF, p_MAT_COLPOZ, P_POS_NODO, P_POS_SUP, P_BLOCCO, P_LAYER, P_FOTOPOZEST, P_FOTOPOZINT, C_DH, c_INI_ID, c_FIN_ID, C_OBJ_ID, C_ISTAT_ID, C_CODE, C_IDPUNINI, C_IDPUNFIN, C_IDLININI, C_ALT_LIN, C_LARGH_LIN, C_QUOINI, C_QUOFIN, C_DISLINI, C_DISLFIN, C_TIPFOG, C_TIPLINIDR, C_POS_TRATTA, C_POS_SUP, C_FOTOINT, C_TNOTE, C_TLUNG, C_PENDENZA, C_DEN_TRONCO, C_LAYER, C_SECONDARY, C_MATERIALE, C_FORMA, C_TIPOFOGNA)
SELECT distinct
P.OBJECTID AS P_OBJECTID, 
P.ISTAT_ID AS P_ISTAT_ID ,
P.QUOINFPOZ AS P_QUOINFPOZ, 
P.QUOPUN AS P_QUOPUN, 
P.QUOTERR AS P_QUOTERR, 
P.QUOTRAVASO AS P_QUOTRAVASO, 
P.TRAVASO AS P_TRAVASO, 
P.SPES_SUP AS P_SPES_SUP, 
P.LARG_CHIU AS P_LARG_CHIU,
P.LUNG_CHIU AS P_LUNG_CHIU,
P.LARG_SUP AS P_LARG_SUP, 
P.LUNG_SUP AS P_LUNG_SUP, 
P.LARG_INF AS P_LARG_INF, 
P.LUNG_INF AS P_LUNG_INF, 
P.COP_CHIU AS P_COP_CHIU, 
P.APP_CHIU AS P_APP_CHIU, 
P.COLPOZ AS P_COLPOZ, 
CODE.DESCRIZIONE AS p_CODE,
FS.FORM AS  p_FORMA_SUP,
FI.FORM AS  p_FORMA_INF,
FC.FORM AS  p_FORM_CHIU,
MAT_CHIU.DESCRIZIONE AS p_MAT_CHIU, 
MAT_SUP.DESCRIZIONE AS p_MAT_SUP,
MAT_INF.DESCRIZIONE AS p_MAT_INF, 
MAT_COLPOZ.DESCRIZIONE AS p_MAT_COLPOZ,
POS_NODO.DESCRIZIONE  as P_POS_NODO, 
POS_SUP.MAT  as P_POS_SUP,
P.BLOCCO AS P_BLOCCO, 
P.LAYER AS P_LAYER, 
P.FOTOPOZEST AS P_FOTOPOZEST, 
P.FOTOPOZINT AS P_FOTOPOZINT,
C.DH as C_DH, 
c.INI_ID as c_INI_ID, 
c.FIN_ID as c_FIN_ID,
C.OBJ_ID as C_OBJ_ID, 
C.ISTAT_ID as C_ISTAT_ID, 
LCODE.DESCRIZIONE as C_CODE, 
C.IDPUNINI as C_IDPUNINI, 
C.IDPUNFIN as C_IDPUNFIN, 
C.IDLININI as C_IDLININI,  
C.ALT_LIN as C_ALT_LIN, 
C.LARGH_LIN as C_LARGH_LIN, 
C.QUOINI as C_QUOINI, 
C.QUOFIN as C_QUOFIN, 
C.DISLINI as C_DISLINI, 
C.DISLFIN as C_DISLFIN, 
C.TIPFOG as C_TIPFOG, 
C.TIPLINIDR as C_TIPLINIDR, 
C.POS_TRATTA as C_POS_TRATTA, 
C.POS_SUP as C_POS_SUP, 
C.FOTOINT as C_FOTOINT, 
C.TNOTE as C_TNOTE, 
C.TLUNG as C_TLUNG, 
C.PENDENZA as C_PENDENZA, 
C.DEN_TRONCO as C_DEN_TRONCO, 
C.LAYER as C_LAYER, 
C.SECONDARY as C_SECONDARY, 
C.MATERIALE as C_MATERIALE, 
C.FORMA as C_FORMA,
TIPFOG.TIPFOG as C_TIPOFOGNA
FROM
(((((((((((((((((POZZI AS P) 
INNER JOIN POZZI_CONDOTTE AS PC ON (PC.ID_POZZO = P.OBJECTID))
INNER JOIN CONDOTTE AS CO ON (PC.ID_CONDOTTA = CO.ID_KEY))
LEFT OUTER JOIN CODE AS CODE ON (CODE.ID = P.CODE))
LEFT OUTER JOIN FORM AS FS ON (FS.ID = P.FORMA_SUP))
LEFT OUTER JOIN FORM AS FI ON (FI.ID = P.FORMA_INF))
LEFT OUTER JOIN FORM AS FC ON (FC.ID = P.FORM_CHIU))
LEFT OUTER JOIN MAT2 AS MAT_CHIU ON (MAT_CHIU.ID = P.MAT_CHIU))
LEFT OUTER JOIN MAT2 AS MAT_SUP ON (MAT_SUP.ID = P.MAT_SUP))
LEFT OUTER JOIN MAT2 AS MAT_INF ON (MAT_INF.ID = P.MAT_INF))
LEFT OUTER JOIN MAT2 AS MAT_COLPOZ ON (MAT_COLPOZ.ID = P.MAT_COLPOZ))
LEFT OUTER JOIN POS_NODO ON (POS_NODO.ID = P.POS_NODO))
LEFT OUTER JOIN POS_SUP ON (POS_SUP.ID = P.POS_SUP))
inner JOIN POZZI_CONDOTTE on (POZZI_CONDOTTE.ID_POZZO = P.OBJECTID))
inner JOIN CONDOTTE  AS C on (C.ID_KEY = POZZI_CONDOTTE.ID_CONDOTTA))
LEFT OUTER JOIN LCODE ON (LCODE.ID = C.CODE))
LEFT OUTER JOIN TIPFOG ON (TIPFOG.ID = C.TIPFOG))

;
