SELECT 
    X, Y, 
    OBJECTID as "OBJ_ID",
    ISTAT_ID as "ISTAT_ID",
    QUOPUN as "QUOPUN",
    CODE as "CODE",
    FORM_CHIU as "FORMA_CHIU",
    MAT_CHIU as "MAT_CHIU",
    LARG_CHIU as "LARG_CHIU",
    LUNG_CHIU as "LUNG_CHIU",
    FORMA_SUP as "FORMA_SUP",
    MAT_SUP as "MAT_SUP",
    LARG_SUP as "LARG_SUP",
    LUNG_SUP as "LUNG_SUP",
    FORMA_INF as "FORMA_INF",
    LARG_INF as "LARG_INF",
    LUNG_INF as "LUNG_INF",
    MAT_INF as "MAT_INF",
    QUOINFPOZ as "QUOINFPOZ",
    COLPOZ as "COLPOZ",
    TRAVASO as "TRAVASO",
    COP_CHIU as "COP_CHIU",
    APP_CHIU as "APP_CHIU",
    MAT_COLPOZ as "MAT_COLPOZ",
    SUPPOSA as "SUPPOSA",
    POS_NODO as "POS_NODO",
    POS_SUP as "POS_SUP",
    QUOTERR as "QUOTERR",
    QUOTRAVASO as "QUOTRAVASO",
    FOTOPOZEST & ',' & FOTOPOZINT as "IMAGE",
    DISEGNI as "DISEGNI",
    `DATA` as "DATA", 
    TNOTE as "NOTE",
    DEN_PUN as "DEN_PUN",
    SPES_SUP as "SPES_SUP",
	FOTOPOZEST as "FOTO_E",
	FOTOPOZINT as "FOTO_I",
    BLOCCO as "BLOCCO", 
    LAYER as "LAYER"
FROM POZZI;
 
